# SITE PARAMS

# SEO
marketing:
  seo:
    site_type: Person
    org_name: 'Alexa Aringer'
    description: 'Personal academic website of Alexa Aringer, PhD student in Clinical Psychology at the University of Oregon.'
    twitter: ''
  analytics:
    google_analytics: ''

# Site header
header:
  navbar:
    logo:
      text: "Alexa Aringer"

# Site footer
footer:
  copyright:
    notice: '© {year} Alexandra S. Aringer'
